import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutDefault from "./_components/layout-default/LayoutDefault";
import Providers from "@/components/providers/Providers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <LayoutDefault>{children}</LayoutDefault>
        </Providers>
      </body>
    </html>
  );
}
